#!/usr/bin/env python3
"""
Design Token Generator

Generates CSS Custom Properties or JSON token files from a simple config input.
Reads a token config JSON and outputs a ready-to-use token file.

Usage:
    python scripts/token_generator.py config.json --format css
    python scripts/token_generator.py config.json --format json
    python scripts/token_generator.py config.json --format css --output tokens.css

Config format: see resources/audit-schema.json (tokens section)
"""

import json
import sys
import argparse
from pathlib import Path
from datetime import datetime


def flatten_tokens(obj: dict, prefix: str = "") -> list[tuple[str, str]]:
    """Flatten nested token dict into list of (css-variable-name, value) pairs."""
    results = []
    for key, val in obj.items():
        full_key = f"{prefix}-{key}" if prefix else key
        if isinstance(val, dict) and "value" in val:
            results.append((full_key, str(val["value"])))
        elif isinstance(val, dict):
            results.extend(flatten_tokens(val, full_key))
        else:
            results.append((full_key, str(val)))
    return results


def generate_css(config: dict) -> str:
    lines = [
        f"/* Design Tokens — Generated by token_generator.py */",
        f"/* Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M')} */",
        f"/* Project: {config.get('project_name', 'Unnamed')} */",
        "",
        ":root {",
    ]

    sections = {k: v for k, v in config.items()
                if k not in ("project_name", "version") and isinstance(v, dict)}

    for section, tokens in sections.items():
        lines.append(f"\n  /* {section.replace('_', ' ').upper()} */")
        flat = flatten_tokens(tokens, f"--{section.rstrip('s')}")
        for name, value in flat:
            # Normalize variable name: double hyphens, spaces → hyphens
            var_name = f"--{name.lstrip('-').replace('_', '-').replace(' ', '-')}"
            lines.append(f"  {var_name}: {value};")

    lines.append("}")
    return "\n".join(lines)


def generate_json(config: dict) -> str:
    """Output a Style Dictionary-compatible JSON."""
    output = {
        "$schema": "https://style-dictionary.io/schema",
        "metadata": {
            "project": config.get("project_name", "Unnamed"),
            "version": config.get("version", "1.0.0"),
            "generated_at": datetime.now().isoformat(),
        },
        "tokens": {k: v for k, v in config.items()
                   if k not in ("project_name", "version")},
    }
    return json.dumps(output, indent=2)


def main():
    parser = argparse.ArgumentParser(
        description="Generate design token files from a config JSON."
    )
    parser.add_argument("config_file", help="Path to token config JSON")
    parser.add_argument("--format", "-f", choices=["css", "json"], default="css",
                        help="Output format (default: css)")
    parser.add_argument("--output", "-o", default=None,
                        help="Output file path (default: stdout)")
    args = parser.parse_args()

    try:
        with open(args.config_file, "r", encoding="utf-8") as f:
            config = json.load(f)
    except FileNotFoundError:
        print(f"Error: Config file not found — '{args.config_file}'", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in config — {e}", file=sys.stderr)
        sys.exit(1)

    if args.format == "css":
        output = generate_css(config)
    else:
        output = generate_json(config)

    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"✅ Tokens written to '{args.output}'")
    else:
        print(output)


if __name__ == "__main__":
    main()
